### ISSUE TITLE
Upgrade to .net 4.7.2?

### ISSUE THREAD

**Issue by kareem613** [MerlinCooper/iRacingSDK.Net#1]
I've been working on the replay director. It would be nice to be able to use some of the newer C# features but it requires the dependencies to be upgraded too.  Overlays and SDK namely. 
I can submit the PR for this if you're open to the upgrade.

**Comment by MerlinCooper** [comment]
Updated to Framework .net 4.7.2. with commit 6dd81852939fd191b80c3fbdedeaeb8eb158cab9

closes #1

If you are using the NuGet make sure you do upgrade to 1.0.0.42
https://ci.appveyor.com/project/vipoo/iracingsdk-net
